import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Tabview from '../components/home/tabview/Tabview'
import PassengerInfo from '../components/common/passenger-info-form/PassengerInfo'
import Grid from '@mui/material/Grid/Grid'
import { useState } from 'react'
import TabPanel from '../components/home/tabview/TabPanel'



export default function Home() {
  const [value, setValue] = useState<number>(0);
  return (
    <div className={styles.container}>
      <Head>
        <title>Alibaba</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Tabview value={value}setValue={setValue}/>
      <Grid>
        
      </Grid>
      <TabPanel value={value} index={0}></TabPanel>
      <TabPanel value={value} index={1}></TabPanel>
      <TabPanel value={value} index={2}><PassengerInfo/></TabPanel>
      <TabPanel value={value} index={3}></TabPanel>
      <TabPanel value={value} index={4}></TabPanel>
      
    </div>
  )
}
