import Typography from '@mui/material/Typography/Typography'
import Head from 'next/head'
import Image from 'next/image'
import HelpCard from '../components/home/help-card/HelpCard'
import styles from '../styles/Home.module.css'

import Grid from '@mui/material/Grid/Grid'

import LayoutMobile from '../components/layout/layoutMobile/LayoutMobile'
import Tabview from '../components/home/tabview/Tabview'
import BusTicket from '../components/ticket_cards/BusTicket'


export default function Home() {
  return (
    <div className={styles.container}>
      <Grid width={'852px'}>
      <BusTicket/>
      </Grid>
      <Head>
        <title>Alibaba</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <LayoutMobile>214641lkml</LayoutMobile>
      <Tabview/>
      <Grid>

      </Grid>
    </div>
  )
}
